routes/web.php
<?php

Route::get('/', 'BaseController@index')->name('base');

Route::get('/orders', 'Orders\OrdersController@index')->name('orders');

Route::resource('/order', 'Orders\OrdersController');

app/Models/Order_products/Order_products.php
<?php

namespace App\Models\Order_products;

use Illuminate\Database\Eloquent\Model;

class Order_products extends Model
{

    protected $fillable = ['id','order_id','product_id', 'quantity', 
        'price', 'created_at', 'updated_at'];

}

app/Models/Orders/Order.php
<?php

namespace App\Models\Orders;

use Illuminate\Database\Eloquent\Model;
use App\Models\Order_products\Order_products;
use App\Models\Partners\Partner;

class Order extends Model
{

    protected $fillable = ['id','status','client_email', 'partner_id', 
        'delivery_dt', 'created_at', 'updated_at'];

    public function order_products()
    {
      return $this->hasMany(Order_products::class, 'order_id', 'id');
    }

    public function partner()
    {
      return $this->hasMany(Partner::class, 'id', 'partner_id');
    }

    public function products($order_id)
    {
      return self::join('order_products','orders.id', '=', 'order_products.order_id')
        ->join('products', 'order_products.product_id', '=', 'products.id')
        ->where('orders.id', $order_id)
        ->get();
    }

} 

app/Models/Partners/Partner.php
<?php

namespace App\Models\Partners;

use Illuminate\Database\Eloquent\Model;
use App\Models\Orders\Order;

class Partner extends Model
{

    protected $fillable = ['id','email','name', 'created_at', 'updated_at'];

    public function order()
    {
        return $this->belongsTo(Order::class);
    }

}

app/Models/Products/Product.php
<?php

namespace App\Models\Products;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{

    protected $fillable = ['id','name','price', 'vendor_id', 'created_at', 'updated_at'];

}

app/Order.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Order extends Model
{
    //
}

app/OrderProduct.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class OrderProduct extends Model
{
    //
}

app/Partner.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Partner extends Model
{
    //
}

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    //
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Vendor.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Vendor extends Model
{
    //
}

app/Http/Controllers/BaseController.php
<?php

namespace App\Http\Controllers;

use App\Http\Controllers\Controller;
use GuzzleHttp\Exception\GuzzleException;
use GuzzleHttp\Client;

class BaseController extends Controller
{
    public function index()
    {
        // TO DO // transfer to services
        $client = new Client();
        $res = $client->request('GET', 'https://samples.openweathermap.org/data/2.5/weather?q=London&appid=b6907d289e10d714a6e88b30761fae22');
        $pat = "!\":\{(.*)\},!sUi";
        $n = preg_match_all($pat, (string) $res->getBody(), $result);
        if ($n>=1) {
            $pat1 = "!\"(.*)\":(.*),!sUi";
            $n1 = preg_match_all($pat1, $result[1][1], $result1);
            if ($n1>=1) {
                $mainTemperature[$result1[1][0]] = $result1[2][0]-273;
            }
        } 

        return view('base', [
            'wheather' => $mainTemperature
        ]);
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/Orders/OrdersController.php
<?php

namespace App\Http\Controllers\Orders;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Orders\Order;
use App\Models\Partners\Partner;
use DB;

class OrdersController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
   public function index()
   {
        return view('orders', [
            'orders' => Order::orderBy('created_at', 'desc')->paginate(10),
            'partners' => Partner::all()->pluck('name', 'id'),
        ]);
   }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        return view('order', [
            'id'    => $id,
            'order' => Order::find($id),
            'delimiter'  => ''
          ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Order $order)
    {
        $order->update($request->all());
        DB::update('update partners set name = ? where id = ?', [$request->name, $request->partner_id]);

        return  redirect()->route('order.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/base.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="title m-b-md">
        Avangard
    </div>
    <ul class="list-group">
        <li class="list-group-item d-flex justify-content-between align-items-center">
            Weather in London
            <span class="badge badge-primary badge-pill">
                {!! $wheather['temp'] !!} degrees Celsius
            </span>
        </li>
    </ul>
    <div class="list-group">
    <a href="{{route('orders')}}" class="list-group-item active">
        <span class="glyphicon glyphicon-star"></span> Заказы <span class="badge">10</span>
    </a>
    <a href="#" class="list-group-item">
        <span class="glyphicon glyphicon-user"></span> Пользователи <span class="badge">24</span>
    </a>
    <a href="#" class="list-group-item">
        <span class="glyphicon glyphicon-th-list"></span> Статьи <span class="badge">411</span>
    </a>
    <a href="#" class="list-group-item">
        <span class="glyphicon glyphicon-camera"></span> Изображение <span class="badge">25</span>
    </a>
</div>
</div>
<!-- Scripts -->
<script src="{{ asset('js/app.js') }}"></script>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>{{ config('app.name', 'Laravel') }}</title>
    <!-- Styles -->
    <link href="{{ asset('css/bootstrap.css') }}" rel="stylesheet">
    <style>
        .title {
            font-size: 56px;
        }
        .m-b-md {
            margin-bottom: 30px;
        }
    </style>
</head>
<body>
@yield('content')
    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}"></script>
</body>
</html>
    <!-- CSRF Token -->
    

resources/views/order.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
<form class="form-horizontal" action="{{route('order.update', $order)}}" method="post">
    <input type="hidden" name="_method" value="put">
    <input type="hidden" name="partner_id" value="{{$order->partner_id}}">
    {{ csrf_field() }}
    <table class="table table-striped">
        <thead>
            <tr>
            <th>email_клиента</th>
            <th>партнер</th>
            <th>статус заказа</th>
            <th>продукты</th>
            <th>стоимость заказа</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td><input type="text" class="form-control" name="client_email" placeholder="Заголовок категории" value="{!! $order->client_email !!}"></td>
                <td>
                    @foreach ($order->partner as $partner)
                    <input type="text" class="form-control" name="name" placeholder="Заголовок категории" value="{{ $partner->name }}">
                    @endforeach
                </td>
                <td>
                    <select class="form-control" name="status">
                        @if ($order->status == 0)
                            <option value="0" selected="">Новый</option>
                            <option value="10">Подтвержден</option>
                            <option value="20">Завершен</option>
                        @elseif ($order->status == 10)
                            <option value="10" selected="">Подтвержден</option>
                            <option value="0">Новый</option>
                            <option value="20">Завершен</option>
                        @elseif ($order->status == 20)
                            <option value="20" selected="">Завершен</option>
                            <option value="0">Новый</option>
                            <option value="10">Подтвержден</option>
                        @else
                            <option value="">Статус не определен</option>
                        @endif
                    </select>
                </td>
                <td>
                    @forelse ($order->products($order->id) as $product)
                        <li>{{ $product->name }}</li>
                    @empty
                        Данные отсутствуют
                    @endforelse
                </td>
                <td>
                    @forelse ($order->products($order->id) as $product)
                        <li>{{ $product->price }}</li>
                    @empty
                        Данные отсутствуют
                    @endforelse
                </td>
            </tr>
        </tbody>
    </table>
    <input class="btn btn-primary" type="submit" value="Сохранить">
  </form>
</div>
<!-- Scripts -->
<script src="{{ asset('js/app.js') }}"></script>
@endsection

resources/views/orders.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
  <table class="table table-striped">
  <thead>
      <tr>
        <th>ID</th>
        <th>Partners name</th>
        <th>Price</th>
        <th>Name products</th>
        <th>Status</th>
      </tr>
    </thead>
    <tbody>
      @forelse ($orders as $order)
        <tr>
          <td><a href="{{route('order.edit', $order->id)}}" target="_blank">{!! $order->id !!}</a></td>
          <td>{!! $partners[$order->partner_id] !!}</td>
          <td>
            @forelse ($order->order_products as $order_product)
            <li>{!! $order_product->price !!}</li>
            @empty
              ---
            @endforelse
          </td>
          <td>
            @forelse ($order->products($order->id) as $product)
              <li>{{ $product->name }}</li>
            @empty
              ---
            @endforelse
          </td>
          <td>
            @if ($order->status == 0)
              Новый
            @elseif ($order->status == 10)
              Подтвержден
            @elseif ($order->status == 20)
              Завершен
            @else
              Статус не определен.
            @endif
          </td>
        </tr>
      @empty
        <tr>
          <td colspan="3" class="text-center"><h2>Данные отсутствуют</h2></td>
        </tr>
      @endforelse
    </tbody>
    <tfoot>
        <tr>
            <td colspan="3">
                <ul class="pagination pull-right">
                    {{$orders->links()}}
                </ul>
            </td>
        </tr>
    </tfoot>
  </table>
</div>
<!-- Scripts -->
<script src="{{ asset('js/app.js') }}"></script>
@endsection